#version 430
layout (local_size_x = 4, local_size_y = 4, local_size_z = 4) in;
layout (rgba32f, binding = 0) uniform image3D test3D;

void main()
{
	ivec3 dims = imageSize (test3D);
	vec4 pixel = vec4 (0.0, 0.0, 0.0, 1.0);
	ivec3 pixel_coords = ivec3(gl_GlobalInvocationID.xyz);
	
	pixel = vec4(pixel_coords.x/dims.x, pixel_coords.y/dims.y, pixel_coords.z/dims.z, 1.0);
	
	
	imageStore (test3D, pixel_coords, pixel);
}
